var Algs = (function () {
    sets = {
        cmll: { name: "CMLL", source: "https://sites.google.com/view/kianroux/cmll", algs: [
            { id: "o_adjacent_swap", alg: "R U R' F' R U R' U' R' F R2 U' R'", kind: "cmll" },
            { id: "o_diagonal_swap", alg: "r2 D r' U r D' R2 U' F' U' F", kind: "cmll" },
            { id: "h_columns", alg: "R U2 R' U' R U R' U' R U' R'", kind: "cmll" },
            { id: "h_rows", alg: "F R U R' U' R U R' U' R U R' U' F'", kind: "cmll" },
            { id: "h_column", alg: "U R U2' R2' F R F' U2 R' F R F'", kind: "cmll" },
            { id: "h_row", alg: "r U' r2' D' r U' r' D r2 U r'", kind: "cmll" },
            { id: "pi_right_bar", alg: "F R U R' U' R U R' U' F'", kind: "cmll" },
            { id: "pi_back_slash", alg: "U F R' F' R U2 R U' R' U R U2' R'", kind: "cmll" },
            { id: "pi_x_checkerboard", alg: "U' R' F R U F U' R U R' U' F'", kind: "cmll" },
            { id: "pi_forward_slash", alg: "R U2 R' U' R U R' U2' R' F R F'", kind: "cmll" },
            { id: "pi_columns", alg: "U' r U' r2' D' r U r' D r2 U r'", kind: "cmll" },
            { id: "pi_left_bar", alg: "U' R' U' R' F R F' R U' R' U2 R", kind: "cmll" },
            { id: "u_forward_slash", alg: "U2 R2 D R' U2 R D' R' U2 R'", kind: "cmll" },
            { id: "u_back_slash", alg: "R2' D' R U2 R' D R U2 R", kind: "cmll" },
            { id: "u_front_row", alg: "R2' F U' F U F2 R2 U' R' F R", kind: "cmll" },
            { id: "u_rows", alg: "U' F R2 D R' U R D' R2' U' F'", kind: "cmll" },
            { id: "u_x_checkerboard", alg: "U2 r U' r' U r' D' r U' r' D r", kind: "cmll" },
            { id: "u_back_row", alg: "U' F R U R' U' F'", kind: "cmll" },
            { id: "t_left_bar", alg: "U' R U R' U' R' F R F'", kind: "cmll" },
            { id: "t_right_bar", alg: "U L' U' L U L F' L' F", kind: "cmll" },
            { id: "t_rows", alg: "F R' F R2 U' R' U' R U R' F2", kind: "cmll" },
            { id: "t_front_row", alg: "r' U r U2' R2' F R F' R", kind: "cmll" },
            { id: "t_back_row", alg: "r' D' r U r' D r U' r U r'", kind: "cmll" },
            { id: "t_columns", alg: "U2 r2' D' r U r' D r2 U' r' U' r", kind: "cmll" },
            { id: "s_left_bar", alg: "U R U R' U R U2 R'", kind: "cmll" },
            { id: "s_x_checkerboard", alg: "U L' U2 L U2' L F' L' F", kind: "cmll" },
            { id: "s_forward_slash", alg: "U F R' F' R U2 R U2' R'", kind: "cmll" },
            { id: "s_Columns", alg: "U2 R' U' R U' R2' F' R U R U' R' F U2' R", kind: "cmll" },
            { id: "s_right_bar", alg: "U' R U R' U R' F R F' R U2' R'", kind: "cmll" },
            { id: "s_back_slash", alg: "U R U' L' U R' U' L", kind: "cmll" },
            { id: "as_right_bar", alg: "U R' U' R U' R' U2' R", kind: "cmll" },
            { id: "as_columns", alg: "U' R2 D R' U R D' R' U R' U' R U' R'", kind: "cmll" },
            { id: "as_back_slash", alg: "U' F' L F L' U2' L' U2 L", kind: "cmll" },
            { id: "as_x_checkerboard", alg: "U' R U2' R' U2 R' F R F'", kind: "cmll" },
            { id: "as_forward_slash", alg: "U' L' U R U' L U R'", kind: "cmll" },
            { id: "as_left_bar", alg: "R' U' R U' R' U R' F R F' U R", kind: "cmll" },
            { id: "l_mirror", alg: "F R U' R' U' R U R' F'", kind: "cmll" },
            { id: "l_inverse", alg: "F R' F' R U R U' R'", kind: "cmll" },
            { id: "l_pure", alg: "R U2 R' U' R U R' U' R U R' U' R U' R'", kind: "cmll" },
            { id: "l_front_commutator", alg: "R U2 R D R' U2 R D' R2'", kind: "cmll" },
            { id: "l_diag", alg: "R' U' R U R' F' R U R' U' R' F R2", kind: "cmll" },
            { id: "l_back_commutator", alg: "U R' U2 R' D' R U2 R' D R2", kind: "cmll" }]
        },
        coll: { name: "COLL", source: "http://www.cyotheking.com/coll", algs: [
            { id: "s_1", alg: "R U R' U R U2 R'", kind: "coll" },
            { id: "s_2", alg: "U' R U R' U R U' R D R' U' R D' R2'", kind: "coll" },
            { id: "s_3", alg: "U2 R U R' U R2 D R' U2 R D' R2'", kind: "coll" },
            { id: "s_4", alg: "F' R U2 R' U2 R' F2 R U R U' R' F'", kind: "coll" },
            { id: "s_5", alg: "L' R U R' U' L U2 R U2 R'", kind: "coll" },
            { id: "s_6", alg: "R U' L' U R' U' L", kind: "coll" },
            { id: "as_1", alg: "R' U' R U' R' U2 R", kind: "coll" },
            { id: "as_2", alg: "U2 R U2 R' U2 L' U R U' R' L", kind: "coll" },
            { id: "as_3", alg: "U2 R2 D R' U R D' R' U R' U' R U' R'", kind: "coll" },
            { id: "as_4", alg: "R' U L U' R U L'", kind: "coll" },
            { id: "as_5", alg: "U2 R2 D R' U2 R D' R2 U' R U' R'", kind: "coll" },
            { id: "as_6", alg: "R U' R' U2 R U' R' U2 R' D' R U R' D R", kind: "coll" },
            { id: "t_1", alg: "r U R' U' r' F R F'", kind: "coll" },
            { id: "t_2", alg: "U' R' F R U R' U' R' F' R2 U' R' U2 R", kind: "coll" },
            { id: "t_3", alg: "U2 l' U' L U R U' r' F", kind: "coll" },
            { id: "t_4", alg: "U' F R U R' U' R U' R' U' R U R' F'", kind: "coll" },
            { id: "t_5", alg: "U R U2 R' U' R U' R2 U2 R U R' U R", kind: "coll" },
            { id: "t_6", alg: "U' R U' R2' D' r U2 r' D R2 U R'", kind: "coll" },
            { id: "u_1", alg: "R2 D R' U2 R D' R' U2 R'", kind: "coll" },
            { id: "u_2", alg: "U2 R' F R U' R' U' R U R' F' R U R' U' R' F R F' R", kind: "coll" },
            { id: "u_3", alg: "U2 R2' D' R U2 R' D R U2 R", kind: "coll" },
            { id: "u_4", alg: "R' F2 R U2 R U2 R' F2 R U2 R'", kind: "coll" },
            { id: "u_5", alg: "R U R' U R U2 R2 U' R U' R' U2 R", kind: "coll" },
            { id: "u_6", alg: "U2 R2 D' R U R' D R U R U' R' U' R", kind: "coll" },
            { id: "l_1", alg: "F' r U R' U' r' F R", kind: "coll" },
            { id: "l_2", alg: "U R' U' R U R' F' R U R' U' R' F R2", kind: "coll" },
            { id: "l_3", alg: "U' F R' F' r U R U' r'", kind: "coll" },
            { id: "l_4", alg: "U' R U2 R D R' U2 R D' R2", kind: "coll" },
            { id: "l_5", alg: "R' U' R U' R' U R U' R' U R U' R' U2 R", kind: "coll" },
            { id: "l_6", alg: "U2 R' U2 R' D' R U2 R' D R2", kind: "coll" },
            { id: "pi_1", alg: "R U2 R2' U' R2 U' R2' U2' R", kind: "coll" },
            { id: "pi_2", alg: "R U R' U' R' F R2 U R' U' R U R' U' F'", kind: "coll" },
            { id: "pi_3", alg: "R' F2 R U2 R U2 R' F2 U' R U' R'", kind: "coll" },
            { id: "pi_4", alg: "r U' r' U' r U r' U' x' R2 U' R' U R' x", kind: "coll" },
            { id: "pi_5", alg: "U F U R U' R' U R U2 R' U' R U R' F'", kind: "coll" },
            { id: "pi_6", alg: "R U D' R U R' D R2 U' R' U' R2' U2' R", kind: "coll" },
            { id: "h_1", alg: "R U R' U R U' R' U R U2 R'", kind: "coll" },
            { id: "h_2", alg: "U' F R U R' U' R U R' U' R U R' U' F'", kind: "coll" },
            { id: "h_3", alg: "F R U' R' U R U2 R' U' R U R' U' F'", kind: "coll" },
            { id: "h_4", alg: "R' F' R U2 R U2 R' F U' R U' R'", kind: "coll" }]
        }
    }

    return {
        sets: sets
    };
}());